// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkgymbyswyhxakishqej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrZ3ltYnlzd3loeGFraXNocWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDU1NDcsImV4cCI6MjA2NzEyMTU0N30.CLeqEp5Gmyp4u0W2ZR_jDPJSLgc22k9G-KYXWQIxaLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});